name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        # Version of PostgreSQL to use
        postgresql version: 11 # optional, default is latest
        # POSTGRES_DB - name for the default database that is created
        postgresql db: vapor_database # optional, default is 
        # POSTGRES_USER - create the specified user with superuser power
        postgresql user: vapor_username # optional, default is 
        # POSTGRES_PASSWORD - superuser password
        postgresql password: vapor_password # optional, default is 
    - name: Run tests
      run: swift test -v
